# Calculating Labor-Values using Gauss-Seidel to Solve the Inverse-Leontief Matrix


In general, let x1, x2, . . ., xn, be the total output of industry S1, S2, . . ., Sn,
respectively. Then


x1 = a11 x1 + a12 x1 + · · · + a1n x1 + b1
x2 = a21 x1 + a22 x1 + · · · + a2n x2 + b2
. . .
xn = an1 x1 + an2 x1 + · · · + ann xn + bn ,

since aij xj is the number of units produced by industry Si and consumed by industry Sj.

X = AX + B 
InX − AX = B
(In − A)X = B
X = (In − A)−1 . B

## Simplest Case : artificial open economy 

### Thank you to Paul Cockshott for providing the cleaned-up data. 


| Industry      | Raw Materials | Services | Manufacturing |  Demand |
|---------------|---------------|----------|---------------|---      |
| Raw Materials | 0.02          | 0.04     | 0.04          | 400  |
| Services      | .05           | .03      | 0.01          | 200  |
| Manufacturing | .2            | .01      | .1            | 600  |


At such a small scale the procedure is very simple. 

We want to solve for AX+b=X 


In [6]:
import numpy as np
import pandas as pd

A=np.array([[.02, .04, .04],
            [.05, .03, .01],
            [.2, .01,.1]])

b=np.array([400,200,600])


def Inverse_Leontief(A,b):
    
    """gauss-seidel to solve system of equations
    
    Parameters
    ..........
    
    
    Returns
    ..........

    """
    n=A.shape[0]
    solution=np.linalg.inv(np.eye(n,n) - A).dot(b)
    return solution
    
Inverse_Leontief(A,b)

array([449.24105739, 237.27154279, 769.13436323])

## Gauss-Seidel 

![image](https://wikimedia.org/api/rest_v1/media/math/render/svg/5815855c28d0f03d019e2662ad2f74aa20fca8ce)

where 

![image2](https://wikimedia.org/api/rest_v1/media/math/render/svg/499e65fdc0563093db6f0d135a9fa0f135e31d0b) and ![image3](https://wikimedia.org/api/rest_v1/media/math/render/svg/07bfa5ff410e80c64664b0126cba0a878385c266)

In [7]:
def gauss(A,b,n_iterations):
    
    """gauss-seidel to solve system of equations
    
    Parameters
    ..........
    
    
    Returns
    ..........
    
    """
    m=b.shape[0]
    L = np.tril(A)
    U = A - L
    T= -np.linalg.inv(L).dot(U)
    C= np.linalg.inv(L).dot(b)
    x=np.random.randint(0,1,(m,1))
    xn=x
    for i in range(n_iterations):
        xn=T.dot(xn) + C[:,np.newaxis]
    
    return(xn)

array([[  929200.        ],
       [-1460318.51851852],
       [-1706368.14814815]])

In [11]:

## diagonally dominant 
A=np.array([[3,-2,1],[1,-3,2],[-1,2,4]]); b=np.array([11,13,2])
display(np.linalg.inv(A).dot(b))
gauss(A,b,100)
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]]); b=np.array([11,13,2])
display(np.linalg.inv(A).dot(b))
gauss(A,b,100)


array([ 1.2972973 , -2.51351351,  2.08108108])

array([15.25, 19.5 , 10.75])

array([[15.25],
       [19.5 ],
       [10.75]])

In [12]:
file='/Users/djamillakhdarhamina/Desktop/io.csv'
with open(file, 'rt') as f:
    data=pd.read_csv(f,index_col=0)
    
data

Agriculture, forestry & fishing  \
Agriculture, forestry & fishing                                   3327   
Mining & quarrying                                                   9   
Food, beverages & tobacco                                         2137   
Textiles, apparel & leather                                         92   
Wood products & furniture                                           42   
Paper, paper products & printing                                   169   
Industrial chemicals                                              1020   
Drugs & medicines                                                   31   
Petroleum & coal products                                          169   
Rubber & plastic products                                          125   
Non-metallic mineral products                                       79   
Iron & steel                                                        33   
Non-ferrous metals                                                  14   
Metal products                                                      56   
Non-electrical machinery                                           154   
Office & computing machinery                                        13   
Electrical apparatus, nec                                           20   
Radio, TV & communication equipment                                 14   
Shipbuilding & repairing                                            28   
Other transport                                                      7   
Motor vehicles                                                      46   
Aircraft                                                             6   
Professional goods                                                   9   
Other manufacturing                                                 23   
Electricity, gas & water                                           339   
Construction                                                       244   
Wholesale & retail trade                                          1032   
Restaurants & hotels                                                33   
Transport & storage                                                133   
Communication                                                      154   
Finance & insurance                                                420   
Real estate & business services                                    404   
Community, social & personal services                              389   
Producers of government services                                     0   
Other producers                                                      0   
Statistical discrepancy                                              0   
Total                                                            10771   
Compensation of employees                                         3085   
Gross operating surplus                                           5627   
Indirect taxes, net                                                206   
Sales by final buyers                                               22   
Value added                                                       8940   
Gross output                                                     19711   

                                       Mining & quarrying  \
Agriculture, forestry & fishing                         0   
Mining & quarrying                                    881   
Food, beverages & tobacco                              28   
Textiles, apparel & leather                             2   
Wood products & furniture                              40   
Paper, paper products & printing                       28   
Industrial chemicals                                   50   
Drugs & medicines                                       4   
Petroleum & coal products                              13   
Rubber & plastic products                              46   
Non-metallic mineral products                           6   
Iron & steel                                      

In [405]:
data.corr()

Agriculture, forestry & fishing  \
Agriculture, forestry & fishing                               1.000000   
Mining & quarrying                                            0.947534   
Food, beverages & tobacco                                     0.961208   
Textiles, apparel & leather                                   0.940899   
Wood products & furniture                                     0.904635   
Paper, paper products & printing                              0.945032   
Industrial chemicals                                          0.956022   
Drugs & medicines                                             0.975241   
Petroleum & coal products                                     0.912018   
Rubber & plastic products                                     0.953097   
Non-metallic mineral products                                 0.962108   
Iron & steel                                                  0.964072   
Non-ferrous metals                                            0.924261   
Metal products                                                0.952704   
Non-electrical machinery                                      0.971258   
Office & computing machinery                                  0.935224   
Electrical apparatus, nec                                     0.762751   
Radio, TV & communication equipment                           0.967605   
Shipbuilding & repairing                                      0.903499   
Other transport                                               0.906624   
Motor vehicles                                                0.929909   
Aircraft                                                      0.937618   
Professional goods                                            0.723076   
Other manufacturing                                           0.979370   
Electricity, gas & water                                      0.913460   
Construction                                                  0.954255   
Wholesale & retail trade                                      0.955081   
Restaurants & hotels                                          0.974251   
Transport & storage                                           0.956138   
Communication                                                 0.932756   
Finance & insurance                                           0.959432   
Real estate & business services                               0.948857   
Community, social & personal services                         0.948372   
Producers of government services                              0.669161   
Other producers                                                    NaN   
Statistical discrepancy                                            NaN   
Total                                                         0.971470   
Private domestic consumption                                  0.882466   
Government consumption                                        0.745424   
Total GFCF                                                    0.769870   
Changes in Stocks                                            -0.616333   
Exports of goods and services                                 0.837236   
Total final demand                                            0.851219   
Imports of goods and services                                -0.830752   
Gross output                                                  0.966228   

                                       Mining & quarrying  \
Agriculture, forestry & fishing                  0.947534   
Mining & quarrying                               1.000000   
Food, beverages & tobacco                        0.844635   
Textiles, apparel & leather                      0.878442   
Wood products & furniture                        0.823004   
Paper, paper products & printing                 0.896076   
Industrial chemicals                             0.881689   
Drugs & medicines                                0.963642   
Petroleum & coal products                        0.878912   
Rubber & plastic product

In [204]:
pd.read_csv?

In [ ]:
# io_index_values=data.index.values[1:]
# name_index_values=data['Industries/Commodities'].values[1:]

# io_column_values=data.columns.values[1:]
# name_column_values=data.iloc[0,1:].values
# val=data.iloc[1:,1:].values

# indexes=pd.MultiIndex.from_arrays([io_index_values,name_index_values], names=['IOCode','Name'])
# columns=pd.MultiIndex.from_arrays([io_column_values,name_column_values], names=['Industry_Code','Industry_Name'])

# data_indexed=pd.DataFrame(val, index=indexes, columns=columns)
# data_indexed