# Calculating Labor-Values using Gauss-Seidel to Solve the Inverse-Leontief Matrix


## Simplest Case : artificial open economy 


| Industry      | Raw Materials | Services | Manufacturing |  Compensation|
|---------------|---------------|----------|---------------|---      |
| Raw Materials | 0.02          | 0.04     | 0.04          | 400  |
| Services      | .05           | .03      | 0.01          | 200  |
| Manufacturing | .2            | .01      | .1            | 600  |


At such a small scale the procedure is very simple. 

In [2]:
import numpy as np
import pandas as pd

A=np.array([[.02, .04, .04],
            [.05, .03, .01],
            [.2, .01,.1]])

b=np.array([400,200,600])


def inverse_leontief(A,b):
    
    """gauss-seidel to solve system of equations
    
    Parameters
    ..........
    
    
    Returns
    ..........

    """
    n=A.shape[0]
    solution=np.linalg.inv(np.eye(n,n) - A).dot(b)
    return solution
    
inverse_leontief(A,b)

array([449.24105739, 237.27154279, 769.13436323])

## Iterative Algorithms to Solve Systems of Equations 

## Jacobi

![diagno](https://wikimedia.org/api/rest_v1/media/math/render/svg/b27a04af9ab99bd7ceadf07a6292810ad2703825)

In [7]:
## split into three pieces
def jacobi(A, b,num_iterations):
    D = np.diag(np.diag(A))
    L = np.tril(A,-1)
    U=np.triu(A,1)
    x = np.ones((A.shape[0]))
    xn = x
    for i in range(25):
        xn = np.linalg.inv(D).dot(b - (L + U).dot(xn))
    return xn


## Gauss-Seidel 

![image](https://wikimedia.org/api/rest_v1/media/math/render/svg/5815855c28d0f03d019e2662ad2f74aa20fca8ce)

where 

![image2](https://wikimedia.org/api/rest_v1/media/math/render/svg/499e65fdc0563093db6f0d135a9fa0f135e31d0b) and ![image3](https://wikimedia.org/api/rest_v1/media/math/render/svg/07bfa5ff410e80c64664b0126cba0a878385c266)

In [36]:
def gauss(A,b,n_iterations):
    
    """gauss-seidel to solve system of equations
    
    Parameters
    ..........
    
    
    Returns
    ..........
    
    """
    m=A.shape[0]
    L = np.tril(A)
    U = A - L
    T= -np.linalg.inv(L).dot(U)
    C= np.linalg.inv(L).dot(b)
    x=np.random.randint(0,1,(m,1))
    xn=x
    for i in range(n_iterations):
        xn=T.dot(xn) + C[:,np.newaxis]
    
    return(xn)

In [209]:
## unit tests 

## diagonally dominant 
A=np.array([[3,-2,1],[1,-3,2],[-1,2,4]]); b=np.array([11,13,2])
display(np.linalg.inv(A).dot(b))
display(gauss(A,b,10))

## positive-definite 
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]]); b=np.array([11,13,2])
display(np.linalg.inv(A).dot(b))
display(gauss(A,b,10))

A=np.array([[2,1],[5,7]]); b=np.array([11,13])
jacobi(A,b,25)


D = np.diag(np.diag(A))
L = np.tril(A)
U = A - L
x = np.ones((A.shape[0]))
xn = x
for i in range(num_iterations):
    xn = np.linalg.inv(D).dot(b - (L + U).dot(xn))
return xn

array([ 1.2972973 , -2.51351351,  2.08108108])

array([[ 1.29665834],
       [-2.51326048],
       [ 2.08079482]])

array([15.25, 19.5 , 10.75])

array([[15.22998047],
       [19.47998047],
       [10.73999023]])

array([53665.60631505, 64139.30472593])

## Real Economy 

### Thank you to Paul Cockshott for providing the cleaned-up data. 

In [3]:
file='/Users/djamillakhdarhamina/Desktop/io.csv'
with open(file, 'rt') as f:
    data=pd.read_csv(f,index_col=0)
    
data

Agriculture, forestry & fishing  \
Agriculture, forestry & fishing                                   3327   
Mining & quarrying                                                   9   
Food, beverages & tobacco                                         2137   
Textiles, apparel & leather                                         92   
Wood products & furniture                                           42   
Paper, paper products & printing                                   169   
Industrial chemicals                                              1020   
Drugs & medicines                                                   31   
Petroleum & coal products                                          169   
Rubber & plastic products                                          125   
Non-metallic mineral products                                       79   
Iron & steel                                                        33   
Non-ferrous metals                                                  14   
Metal products                                                      56   
Non-electrical machinery                                           154   
Office & computing machinery                                        13   
Electrical apparatus, nec                                           20   
Radio, TV & communication equipment                                 14   
Shipbuilding & repairing                                            28   
Other transport                                                      7   
Motor vehicles                                                      46   
Aircraft                                                             6   
Professional goods                                                   9   
Other manufacturing                                                 23   
Electricity, gas & water                                           339   
Construction                                                       244   
Wholesale & retail trade                                          1032   
Restaurants & hotels                                                33   
Transport & storage                                                133   
Communication                                                      154   
Finance & insurance                                                420   
Real estate & business services                                    404   
Community, social & personal services                              389   
Producers of government services                                     0   
Other producers                                                      0   
Statistical discrepancy                                              0   
Total                                                            10771   
Compensation of employees                                         3085   
Gross operating surplus                                           5627   
Indirect taxes, net                                                206   
Sales by final buyers                                               22   
Value added                                                       8940   
Gross output                                                     19711   

                                       Mining & quarrying  \
Agriculture, forestry & fishing                         0   
Mining & quarrying                                    881   
Food, beverages & tobacco                              28   
Textiles, apparel & leather                             2   
Wood products & furniture                              40   
Paper, paper products & printing                       28   
Industrial chemicals                                   50   
Drugs & medicines                                       4   
Petroleum & coal products                              13   
Rubber & plastic products                              46   
Non-metallic mineral products                           6   
Iron & steel                                      

In [49]:
l=data.loc['Compensation of employees',:'Real estate & business services']
A=data.loc[:'Real estate & business services',:'Real estate & business services']
inverse_leontief(A,l)

array([-69.57455016,  33.37338018,  23.55091161,   4.06518091,
         2.49873019,  -2.12695828,  25.09875426,  -6.52772011,
       -12.42392259, -25.74769625,  -5.64194265,  33.76825087,
        -0.14281932, -41.44092835,  -3.82837038,  -4.84521631,
        -8.65450876,   9.81075811, -44.8686354 ,   4.22686639,
         3.30440408,  -0.51193537, -43.97524972,  29.24710517,
        -0.67464244,  -0.12165363,  -6.50234463,  -3.07227594,
        -4.15444985,   2.41763644,   2.25875164,   0.39153986])

In [239]:
gauss(A,l,20)

array([[-8.84673149e+12],
       [ 1.99757273e+13],
       [ 4.62455240e+13],
       [ 7.00265058e+12],
       [ 3.93365476e+12],
       [-8.29995603e+12],
       [ 8.26902015e+12],
       [-2.09839578e+13],
       [-2.09364293e+13],
       [-1.01970284e+14],
       [-9.07606487e+12],
       [ 9.08791789e+12],
       [-1.26722939e+12],
       [-3.51169306e+13],
       [-1.29459494e+12],
       [-5.48111943e+11],
       [-1.40356690e+13],
       [-2.49623747e+12],
       [-4.02541933e+13],
       [ 8.72654422e+12],
       [ 8.66744306e+11],
       [ 1.09161036e+11],
       [ 1.56225407e+13],
       [ 6.42773852e+13],
       [ 4.90553554e+11],
       [-1.05304238e+10],
       [ 1.26700228e+13],
       [-4.73107169e+14],
       [ 1.13725661e+13],
       [ 1.21185606e+14],
       [ 1.19909345e+13],
       [ 8.54188400e+12],
       [ 9.02211404e+12]])

In [240]:
jacobi(A.values,l.values,25)

array([-1.02316775e+19, -1.62612715e+19, -1.07824708e+19, -3.47764091e+18,
       -2.06339770e+18, -4.59317118e+18, -3.57688602e+18, -4.69999868e+18,
       -1.27924813e+19, -1.74684026e+19, -4.69872785e+18, -3.46579963e+18,
       -3.26792265e+18, -9.72996864e+18, -2.57654634e+18, -9.84228722e+17,
       -8.44734341e+18, -2.17906082e+18, -9.64581448e+18, -4.73450423e+18,
       -2.16280772e+18, -2.18209271e+17, -1.65171667e+19, -2.02138865e+19,
       -1.39357392e+18, -3.32121674e+17, -1.06397517e+19, -9.96754324e+19,
       -7.10848002e+18, -1.51070296e+19, -4.46627276e+18, -4.87584115e+18,
       -1.77134557e+18])

In [48]:
l=data.loc['Total ',:'Community, social & personal services']
A=data.loc[:'Community, social & personal services',:'Community, social & personal services']
inverse_leontief(A.values, l.values)
jacobi(A.values,l.values, 20)

array([1.81020065e+18, 2.87696365e+18, 1.90764767e+18, 6.15268400e+17,
       3.65058795e+17, 8.12629352e+17, 6.32826964e+17, 8.31529402e+17,
       2.26326113e+18, 3.09053074e+18, 8.31304565e+17, 6.13173426e+17,
       5.78164793e+17, 1.72143772e+18, 4.55845667e+17, 1.74130926e+17,
       1.49451412e+18, 3.85522054e+17, 1.70654906e+18, 8.37634165e+17,
       3.82646535e+17, 3.86058458e+16, 2.92223693e+18, 3.57626504e+18,
       2.46552769e+17, 5.87593648e+16, 1.88239763e+18, 1.76346970e+19,
       1.25764081e+18, 2.67275378e+18, 7.90178332e+17, 8.62639662e+17,
       3.13388583e+17])

In [80]:
file='/Users/djamillakhdarhamina/Desktop/io-1990.csv'
with open(file, 'rt') as f:
    data=pd.read_csv(f,index_col=0)
    
data

False

In [ ]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

is_pos_def(A)

In [77]:
A=data.loc[:'Community, social & personal services',:]
l=data.loc['Compensation of employees',:]
inverse_leontief(A,l)

array([-6.27373034e+01,  3.50988652e+01,  2.12801003e+01,  4.05866543e+00,
        2.11816233e+00, -4.41340407e-01,  2.44346951e+01, -4.64547919e+00,
       -1.22743818e+01, -2.72117185e+01, -4.85235855e+00,  3.13044798e+01,
        7.46245352e-01, -3.68919441e+01, -4.10618979e+00, -4.24625206e+00,
       -1.25743624e+01,  8.11393878e+00, -4.87304832e+01,  4.03843755e+00,
        3.54367274e+00, -5.01929122e-01, -3.89952468e+01,  2.86136246e+01,
       -7.31386184e-01, -5.17021710e-02, -6.56059837e+00, -2.63018005e+00,
       -4.32487526e+00,  1.07162960e+01, -2.53658972e-01])

In [ ]:
# io_index_values=data.index.values[1:]
# name_index_values=data['Industries/Commodities'].values[1:]

# io_column_values=data.columns.values[1:]
# name_column_values=data.iloc[0,1:].values
# val=data.iloc[1:,1:].values

# indexes=pd.MultiIndex.from_arrays([io_index_values,name_index_values], names=['IOCode','Name'])
# columns=pd.MultiIndex.from_arrays([io_column_values,name_column_values], names=['Industry_Code','Industry_Name'])

# data_indexed=pd.DataFrame(val, index=indexes, columns=columns)
# data_indexed