# Implementing Direct and Indirect Methods of Solving in Julia for IO Tables

In [6]:
using LinearAlgebra
using CSV


In [50]:
data=CSV.read("/Users/djamillakhdarhamina/Desktop/uk-1968.csv")
data

49×32 DataFrames.DataFrame. Omitted printing of 30 columns
│ Row │ Column1                          │ Agriculture, forestry & fishing │
│     │ Union{Missing, String}           │ Union{Missing, Int64}           │
├─────┼──────────────────────────────────┼─────────────────────────────────┤
│ 1   │ Agriculture, forestry & fishing  │ 533                             │
│ 2   │ Mining & quarrying               │ 7                               │
│ 3   │ Food, beverages & tobacco        │ 452                             │
│ 4   │ Textiles, apparel & leather      │ 16                              │
│ 5   │ Wood products & furniture        │ 21                              │
│ 6   │ Paper, paper products & printing │ 4                               │
│ 7   │ Industrial chemicals             │ 159                             │
│ 8   │ Drugs & medicines                │ 10                              │
│ 9   │ Petroleum & coal products        │ 38                              │
│ 10  │ Rubber & plastic products        │ 9                               │
⋮
│ 39  │ Finance & insurance              │ 3                               │
│ 40  │ Real estate & business services  │ 5                               │
│ 41  │ Producers of government services │ 0                               │
│ 42  │ Other producers                  │ 0                               │
│ 43  │ Statistical discrepancy          │ 0                               │
│ 44  │ missing                          │ missing                         │
│ 45  │ C                                │ 1568                            │
│ 46  │ V                                │ 376                             │
│ 47  │ S                                │ 568                             │
│ 48  │ X                                │ 2512                            │
│ 49  │ L                                │ 376                             │

In [55]:
names(data[1:30,2:30])

29-element Array{String,1}:
 "Agriculture, forestry & fishing"
 "Mining & quarrying"
 "Food, beverages & tobacco"
 "Textiles, apparel & leather"
 "Wood products & furniture"
 "Paper, paper products & printing"
 "Industrial chemicals"
 "Drugs & medicines"
 "Petroleum & coal products"
 "Rubber & plastic products"
 "Non-metallic mineral products"
 "Iron & steel"
 "Non-ferrous metals"
 ⋮
 "Radio, TV & communication equipment"
 "Shipbuilding & repairing"
 "Other transport"
 "Motor vehicles"
 "Aircraft"
 "Professional goods"
 "Other manufacturing"
 "Electricity, gas & water"
 "Construction"
 "Wholesale & retail trade"
 "Restaurants & hotels"
 "Transport & storage"

In [60]:
function iterative_labor_calc(A,O,V,n_iterations)
    
    L=ones(length(V))
    
    for i in 1:n_iterations
        O1=sum(A.* L ,dims=2) + V 
        L=O1./O 
    end
    
    return O1
    end 

iterative_labor_calc (generic function with 1 method)

In [61]:
iterative_labor_calc(A,O,V,100000)

MethodError: MethodError: objects of type Array{Float64,2} are not callable
Use square brackets [] for indexing an Array.

In [59]:
function generate_diag_dom_and_positive_def_matrix(size)
    A = rand(Float64,(size,size))
    
    for i in CartesianIndices(A)  
        if i[1] == i[2]
        row=i[1]
        column=i[2]
        A[row,column]= A[row,column] * 100000
        end
    end 
    
    b=rand(Float64,size) * 10000
    x=rand(Float64,size)
    
    return (A,b,x)
    end 
    
A,O,V=generate_diag_dom_and_positive_def_matrix(30)

30-element Array{Float64,1}:
 1688.285787210091
 7704.538919466979
 7041.8222281432445
 2018.232816031429
 4744.3953739977915
 5361.097882889742
 5100.758813144044
 5902.668109104523
 4773.52480607347
   36.629693136196465
 6871.643085853969
 7312.248595922497
 3155.8080310824253
    ⋮
 3516.688234465191
 9951.888245704213
  206.88364567366557
 2816.1714339246437
 2842.1753544652706
 6573.870315747412
 2309.668480930598
 3852.8695280057777
 2172.2544523988695
 7567.808223026462
  256.93672530957554
 4517.4066435383575

In [117]:
L=ones(length(V))

for i in 1:10
    O1=sum(A.* L ,dims=2) + V 
    L=O1./O 
end


O1

30×1 Array{Float64,2}:
      0.8548678922653168
      2.2827719378471486e7
      1.263322480536826e10
      5.457506869961228e17
      2.090072049809584e14
      6.50561339491045e15
      1.9322137558322044e16
      1.1682352343668545e15
      5.055755911015379e15
      3.367188017699872e32
      9.573760587044634e11
      1.5205392263340372e8
      2.3406151254283062e13
      ⋮
      7.643894873741592e12
      8.604665438620256e10
      1.1094495079301887e29
      1.7531679441727094e18
      7.093141037996144e8
      2.1865609171185425e11
      1.2319319179336595e19
      4.137462441022844e11
      2.144256371933317e18
      5.413506357006485e12
      6.6436834697108914e19
 342571.96653079503

In [ ]:
function solve(A,b)
   
    x=inv(A) * b 
    
end

In [ ]:
solve(A,b)

In [ ]:
jacobi(A,b,x,3)

In [ ]:
function ILC(A,O,V,n)
    
    n=O.shape
    ## initialize array of ones 
    L=ones(n)
    
    #L=L[:,np.newaxis]
    
    for i in range(n_iterations): 
            O1= np.sum(A * L,axis=0) + V ## multiply vector L row by row with A, then sum going down 
            L= O1/O ## divide the result of operation above with O 
    
    return O1

In [ ]:
function jacobi(A,b,x,n)
     """ jacobi iteration solving Ax=b
    
    Parameters
    ..........
    
    A: 
      ::Float64
      a 2-dimensional mxm numpy array (matrix) , diagonally-dominant
    
    B:
      ::Float64
      a 1-dimensional mx1 numpy array ,shape (m,) and not (m,1)
      
    num_iterations:
      an integral scalar which indicates number of iterations to run
      
    Returns
    ..........
    x:
     ::Float64
     a 1-dimensional mx1 numpy array ,shape (m,) and not (m,1)

    """
    
    diag=Diagonal(A)
    upper=UpperTriangular(A)
    lower=LowerTriangular(A)
    for i in eachindex(upper)
        if i[1] == i[2]
            row=i[1]
            column=i[2]
            upper[row,column]=0
        end
    end 

    for i in eachindex(lower)
        if i[1] == i[2]
            row=i[1]
            column=i[2]
            lower[row,column]=0
        end
    end
    
    inverse=[i for i in inv(diag)]
    LU=lower+upper
    for i in 1:n
        x= inverse * (b - LU * x)
    end
    
    return x
    
    end 
## 41.5s, for jacobi in python
## 5.71s,, for jacobi in julia

In [ ]:
A,b,x=generate_diag_dom_and_positive_def_matrix(10000)

In [ ]:
function gauss_seidel(A,b,x,n)

    L=LowerTriangular(A)
    U=A-L
    inverse=-inv(L)
    T=inverse * U
    C= inverse * b

    for i in 1:n
        x=T * x + C
    end

    return x
    
    end 

In [ ]:
gauss_seidel(A,b,x,3)

LoadError: syntax: space required before "?" operator